agentName: demoagent0001
envName: dev
agentRuntimeName: demoagent0001_dev
imageRepo: 229560443702.dkr.ecr.us-west-2.amazonaws.com
tag: 2db0e85d92beaeed3a4c6580c3341ab5a2d4c8f4
roleArn: arn:aws:iam::229560443702:role/service-role/AmazonBedrockAgentCoreRuntimeDefaultServiceRole
cloudWatchLogTailRoleArn: arn:aws:iam::229560443702:role/cnoe-refl-cw-logs-tail
agentRuntimeID: demoagent0001_dev-5HVqjACUqm
region: us-west-2



environmentVariables:
  DISABLE_ADOT_OBSERVABILITY: "true"
  OPENAI_API_SECRET: "tenant01/demoagent0001/api_key"
  AGENT_NAME: demoagent0001_dev
  AGENT_ENV: Dev
  LANGFUSE_API_SECRET: prod/langfuse

secrets:
  - name: openapi_key
    vault:
      path: tenant01/demoagent0001
      key: api_key
    awsSecretManager:
      key: "tenant01/demoagent0001/api_key"
    
